#!/bin/sh

exec 2>&1

U=ryan52

if [ "$(id -un)" != "$U" ]; then
    su - "$U" -c "$0"
    exit $?
fi

usage(){
echo "======================================"
echo "Current usage: $(du -sh . | sed 's/\s.*//')"
echo "======================================"
}

cd /git

clean(){
    if [ ! -w . ]; then
	READONLY=t
    else
	READONLY=f
    fi
    if [ "$READONLY" = "t" ]; then
	chmod -R u+w .
    fi
    git prune
    git gc
    git repack -f -A -d --depth=500 --window=500
    git prune
    git gc --aggressive
    if [ "$READONLY" = "t" ]; then
	chmod -R a-w .
    fi
}

usage
for i in `ls | grep -v cleanup`; do cd $i; clean; cd ..; done
usage
