#!/bin/sh

# run as a daemon
# TODO: use start-stop-daemon with the --background option
[ "$1" = "go" ] || exec /usr/local/bin/daemon "$(readlink -f $0)" "go" "$@"
shift
exec 2>&1 >/home/mirror-daemon/mirror-daemon.log
# TODO: use inotify-tools

while true; do
    if [ -f /tmp/update-requested ]; then
	rm /tmp/update-requested
	/home/mirror-daemon/fg-git-tools/update-mirror || touch /tmp/update-requested
    else
	sleep 1
    fi
done
