#!/bin/sh

# run as a daemon
# TODO: use start-stop-daemon with the --background option
[ "$1" = "go" ] || exec /usr/local/bin/daemon "$(readlink -f $0)" "go" "$@"
shift

# TODO: use inotify-tools

while true; do
    if [ -f /tmp/update-requested ]; then
	sudo rm /tmp/update-requested
	/home/ryan52/update-mirror || touch /tmp/update-requested
    else
	sleep 1
    fi
done
