#!/bin/sh

export PATH=.:$PATH
export RTCONFIG=/usr/local/ass/configs/svn/rtrc
export GIT_DIR=./.git
quiet () {
    cat >/dev/null
}
umask u=rwx,g=rwx,o=rx
if [ ! -d $name ]; then
    mkdir $name
    chmod g+ws $name
    cd $name
    git init -q --shared | quiet
    git remote add origin /git/$name
else
    cd $name
fi
git fetch -q origin 2>&1 | quiet
while read oldrev newrev refname; do
    branch=$(basename $refname)
    if [ -f .git/refs/remotes/origin/$branch ]; then # it's a branch
        if [ -f .git/refs/heads/$branch ]; then
            git checkout -q $branch | quiet
            git pull -q origin $branch 2>&1 | quiet
        else
            git checkout -q -b $branch origin/$branch | quiet
        fi
        if echo $branch | grep -q ^release_; then
            $git_tools/rt/RT-close.pl --close
        else
            $git_tools/rt/RT-close.pl --pending
        fi
    else # it's a tag
        { git branch -q -D temptag 2>&1 || true; } | quiet
        git checkout -q -b temptag $branch | quiet
        $git_tools/rt/RT-close.pl --close
    fi
done < $tempfile
git checkout -q master
rm $tempfile
