#!/bin/sh
# TEST
tempfile=$(mktemp)
name=$(basename $(readlink -f $(dirname $(dirname $0))))
git_tools=$(dirname $(readlink -f $0))
cat | tee $tempfile | $git_tools/post-receive-email
cd /tmp/
export PATH=.:$PATH
export RTCONFIG=/usr/local/ass/configs/svn/rtrc
export GIT_DIR=./.git
if [ ! -d $name ]; then
    git clone -q /git/$name
    cd $name
else
    cd $name
    git pull -q
fi
pwd
while read oldrev newrev refname; do
    branch=$(basename $refname)
    if [ -f .git/refs/remotes/origin/$branch ]; then # it's a branch
        if [ -f .git/refs/heads/$branch ]; then
            git checkout $branch
            git pull
        else
            git checkout -b $branch origin/$branch
        fi
        if echo $branch | grep -q ^release_; then
            $git_tools/rt/RT-close.pl --close
        else
            $git_tools/rt/RT-close.pl --pending
        fi
    else # it's a tag
        git branch -D temptag || true
        git checkout -b temptag $branch
        $git_tools/rt/RT-close.pl --close
    fi
done < $tempfile
rm $tempfile
