#!/bin/sh

# pfft. insecure temp file vulnerabilities are awesome.

touch /var/cache/mirror-daemon/update-requested
if [ ! -d /var/cache/mirror-daemon/$1 ]; then
    mkdir -p /var/cache/mirror-daemon/$1
    chown mirror-daemon:www-data /var/cache/mirror-daemon/$1
    chmod g+w /var/cache/mirror-daemon/$1
fi
touch /var/cache/mirror-daemon/$1/$2
