#!/bin/bash

# bashism on <(cmd)

set -e

if [ -n "$(ls /tmp/git/* 2>/dev/null)" ]; then
for i2 in /tmp/git/*; do
    i="$(basename "$i2")"
    if [ ! -d "/git/$i" ]; then
	/home/mirror-daemon/fg-git-tools/vps-create_project --nodesc "$i" </dev/null
	cd "/git/$i"
	echo '[remote "origin"]' >> "/git/$i/config"
	echo "url = dev.freegeek.org:/git/$i" >> "/git/$i/config"
	echo 'fetch = +refs/heads/*:refs/remotes/origin/*' >> "/git/$i/config"
    fi
    cd "/git/$i"
    chmod -R u+w .
    git fetch origin --quiet
    git fetch origin --tags --quiet
    for i3 in $(git ls-remote origin | grep /heads/ | cut -d / -f 3); do git branch -f "$i3" "origin/$i3" >/dev/null; done
    for i3 in $(diff <(git branch | sed 's/^..//') <(git ls-remote origin | grep /heads/ | cut -d / -f 3) | grep '^<' | sed 's/^< //'); do git branch -D "$i3" >/dev/null; done
    echo "Mirror of $(basename $(pwd)): $(ssh $(git config remote.origin.url | awk -F: '{print $1}') cat $(git config remote.origin.url | awk -F: '{print $2}')/description)" > description
    chmod -R a-w .
    cd ..
    rm "$i2"
done
fi
