#!/bin/bash

# Downloaded from: ryan52.info/~ryan52/create_project

# Set your domain name here, as you want it to be displayed:
if hostname -f | grep -q xyzzy; then
    HOSTNAME=git.ryan52.info
    DEV_HOSTNAME="$HOSTNAME"
elif hostname -f | grep -q oahu; then
    HOSTNAME=git.freegeek.org
    DEV_HOSTNAME="dev.freegeek.org"
else
    echo "Unknown host: $(hostname -f)"
    exit 1
fi

usage(){
    echo "Usage: $(basename $0) [--update] projectname|all"
    exit 1
}

update(){
    [ "$UPDATE" = "true" ]
}

description(){
    [ "$DESCRIPTION" = "true" ]
}

UPDATE="false"
DESCRIPTION="true"

if [ "$1" = "--update" ]; then
    PROJECT="$2"
    UPDATE="true"
elif [ "$1" = "--nodesc" ]; then
    PROJECT="$2"
    DESCRIPTION="false"
else
    PROJECT="$1"
fi

if [ -z "$PROJECT" ]; then
    usage
fi

if [ "$PROJECT" = "all" ]; then
    if update; then
	for i in /git/*; do
	    $0 --update $(basename $i)
	done
	exit $?
    else
	usage
    fi
fi

if [ -d "/git/$PROJECT" ] && ! update; then
    echo "Project already exists"
    exit 1
fi

if [ ! -d "/git/$PROJECT" ] && update; then
    echo "Project does not exist"
    exit 1
fi

if ! update; then
    if description; then
	echo -n "Project description: "
	read DESC
	if [ "$?" != "0" ]; then
	    echo "Aborted."
	    exit 1
	fi
    fi
    cd /git
    if [ "$USER" = "mirror-daemon" ]; then
	chmod +w .
	mkdir $PROJECT
	chmod -w .
    else
	sudo mkdir $PROJECT
	sudo chown $USER:$USER $PROJECT
    fi
    cd $PROJECT
    git --bare init --shared
    if description; then
	echo "$DESC" > /git/$PROJECT/description
    fi
fi

echo "git://$HOSTNAME/git/$PROJECT" > /git/$PROJECT/cloneurl
echo "http://$HOSTNAME/git/$PROJECT" >> /git/$PROJECT/cloneurl
echo "$DEV_HOSTNAME:/git/$PROJECT" >> /git/$PROJECT/cloneurl
if [ -f /git/$PROJECT/hooks/post-update.sample ]; then
    mv /git/$PROJECT/hooks/post-update.sample /git/$PROJECT/hooks/post-update
fi
chmod +x /git/$PROJECT/hooks/post-update
touch /git/$PROJECT/git-daemon-export-ok
