#!/bin/bash

# Downloaded from: ryan52.info/~ryan52/create_project

# Set your domain name here, as you want it to be displayed:
HOSTNAME=git.freegeek.org

usage(){
    echo "Usage: $(basename $0) [--update] projectname|all"
    exit 1
}

update(){
    [ "$UPDATE" = "true" ]
}

description(){
    [ "$DESCRIPTION" = "true" ]
}

UPDATE="false"
DESCRIPTION="true"

if [ "$1" = "--update" ]; then
    PROJECT="$2"
    UPDATE="true"
elif [ "$1" = "--nodesc" ]; then
    PROJECT="$2"
    DESCRIPTION="false"
else
    PROJECT="$1"
fi

if [ -z "$PROJECT" ]; then
    usage
fi

if [ "$PROJECT" = "all" ]; then
    if update; then
	for i in /git/*; do
	    $0 --update $(basename $i)
	done
	exit $?
    else
	usage
    fi
fi

if [ -d "/git/$PROJECT" ] && ! update; then
    echo "Project already exists"
    exit 1
fi

if [ ! -d "/git/$PROJECT" ] && update; then
    echo "Project does not exist"
    exit 1
fi

if ! update; then
    if description; then
	echo -n "Project description: "
	read DESC
	if [ "$?" != "0" ]; then
	    echo "Aborted."
	    exit 1
	fi
    fi
    cd /git
    sudo mkdir $PROJECT
    sudo chown $USER:$USER $PROJECT
    cd $PROJECT
    git --bare init --shared
    if description; then
	echo "$DESC" > /git/$PROJECT/description
    fi
fi

echo "git://$HOSTNAME/git/$PROJECT" > /git/$PROJECT/cloneurl
echo "http://$HOSTNAME/git/$PROJECT" >> /git/$PROJECT/cloneurl
echo "$HOSTNAME:/git/$PROJECT" >> /git/$PROJECT/cloneurl
chmod +x /git/$PROJECT/hooks/post-update
touch /git/$PROJECT/git-daemon-export-ok
